name: Daily Tistory Uploader

on:
  schedule:
    - cron: '0 9 * * *'  # 매일 오전 9시 (UTC)
  workflow_dispatch:      # 수동 실행 가능

jobs:
  run-daily-newsletter:
    runs-on: windows-latest  # Windows 환경 사용

    steps:
      # 1. 저장소 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Python 환경 설정
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Chrome 및 ChromeDriver 설치
      - name: Install Chrome and ChromeDriver
        run: |
          choco install googlechrome chromedriver -y
        shell: cmd

      # 4. 의존성 설치
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
        shell: cmd

      # 5. Python 스크립트 실행 (입력값 자동화)
      - name: Run main.py - First Execution
        run: |
          echo 2 | python main.py
          echo 2 | python main.py
        shell: cmd

      - name: Run main.py - Second Execution
        run: |
          echo 1 | python main.py
          echo 2 | python main.py
        shell: cmd
